services:
  postgres-db:
    image: postgres:16
    container_name: simpleapp-db
    networks:
      - simple-app-network
    secrets:
      - postgres_user
      - postgres_pass
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_pass
      POSTGRES_DB: simpleapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./simple-app.sql:/docker-entrypoint-initdb.d/simple-app.sql
    ports:
      - "5435:5435"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 5s

  backend:
    build: ./back
    container_name: simpleapp-backend
    networks:
      - simple-app-network
    depends_on:
      postgres-db:
        condition: service_healthy
    secrets:
      - postgres_user
      - postgres_pass
    env_file:
      - ./back/.env
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://127.0.0.1:8080/users || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 3s
    ports:
      - "8080:8080"

  frontend:
    build: ./front
    container_name: simpleapp-frontend
    ports:
      - "3002:80"

volumes:
  postgres_data:

networks:
  simple-app-network:
    driver: bridge

secrets:
  postgres_user:
    file: ./postgres_user.secret
  postgres_pass:
    file: ./postgres_pass.secret
